name: Deploying

on:
  push: branches:[master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    uses: actions/checkout@v3

    steps:
      - name: executing remote ssh commands using ssh key
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: sh deploy.sh
